/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RootImport } from './routes/root'
import { Route as PacketsImport } from './routes/packets'
import { Route as HomeImport } from './routes/home'
import { Route as DemoImport } from './routes/demo'
import { Route as IndexImport } from './routes/index'
import { Route as NodeNodeIdImport } from './routes/node.$nodeId'

// Create/Update Routes

const RootRoute = RootImport.update({
  id: '/root',
  path: '/root',
  getParentRoute: () => rootRoute,
} as any)

const PacketsRoute = PacketsImport.update({
  id: '/packets',
  path: '/packets',
  getParentRoute: () => rootRoute,
} as any)

const HomeRoute = HomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRoute,
} as any)

const DemoRoute = DemoImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const NodeNodeIdRoute = NodeNodeIdImport.update({
  id: '/node/$nodeId',
  path: '/node/$nodeId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoImport
      parentRoute: typeof rootRoute
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeImport
      parentRoute: typeof rootRoute
    }
    '/packets': {
      id: '/packets'
      path: '/packets'
      fullPath: '/packets'
      preLoaderRoute: typeof PacketsImport
      parentRoute: typeof rootRoute
    }
    '/root': {
      id: '/root'
      path: '/root'
      fullPath: '/root'
      preLoaderRoute: typeof RootImport
      parentRoute: typeof rootRoute
    }
    '/node/$nodeId': {
      id: '/node/$nodeId'
      path: '/node/$nodeId'
      fullPath: '/node/$nodeId'
      preLoaderRoute: typeof NodeNodeIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/home': typeof HomeRoute
  '/packets': typeof PacketsRoute
  '/root': typeof RootRoute
  '/node/$nodeId': typeof NodeNodeIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/home': typeof HomeRoute
  '/packets': typeof PacketsRoute
  '/root': typeof RootRoute
  '/node/$nodeId': typeof NodeNodeIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/home': typeof HomeRoute
  '/packets': typeof PacketsRoute
  '/root': typeof RootRoute
  '/node/$nodeId': typeof NodeNodeIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/demo' | '/home' | '/packets' | '/root' | '/node/$nodeId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/demo' | '/home' | '/packets' | '/root' | '/node/$nodeId'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/home'
    | '/packets'
    | '/root'
    | '/node/$nodeId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRoute
  HomeRoute: typeof HomeRoute
  PacketsRoute: typeof PacketsRoute
  RootRoute: typeof RootRoute
  NodeNodeIdRoute: typeof NodeNodeIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRoute,
  HomeRoute: HomeRoute,
  PacketsRoute: PacketsRoute,
  RootRoute: RootRoute,
  NodeNodeIdRoute: NodeNodeIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/demo",
        "/home",
        "/packets",
        "/root",
        "/node/$nodeId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/demo": {
      "filePath": "demo.tsx"
    },
    "/home": {
      "filePath": "home.tsx"
    },
    "/packets": {
      "filePath": "packets.tsx"
    },
    "/root": {
      "filePath": "root.tsx"
    },
    "/node/$nodeId": {
      "filePath": "node.$nodeId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
